name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'main'
        required: true
  
jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Test Run
        run: echo "Hello world!"
        
        
